Update ticket_number_validater.yml

diff --git a/.github/workflows/ticket_number_validater.yml b/.github/workflows/ticket_number_validater.yml
--- a/.github/workflows/ticket_number_validater.yml
+++ b/.github/workflows/ticket_number_validater.yml
@@ -17,16 +17,13 @@ jobs:
       - name: Check PR Description
         id: check-description
         run: |
-          echo "PR Description: '${{ github.event.pull_request.body }}'"
           pattern="HCPCM-[0-9]+"
-          echo "Pattern: $pattern"
-          if ! grep -qE "$pattern" <<< "${{ github.event.pull_request.title }}"; then
-            echo "Pattern not found!"
-            echo "::set-output name=ticket-missing::true"
-          else
-            echo "Pattern found!"
-          fi
+          title_matched=$(grep -qE "$pattern" <<< "${{ github.event.pull_request.title }}"; echo $?)
+          description_matched=$(grep -qE "$pattern" <<< "${{ github.event.pull_request.body }}"; echo $?)
 
+          if [ "$title_matched" -ne 0 -a "$description_matched" -ne 0 ]; then
+            echo "::set-output name=ticket-missing::true"
+          fi
       - name: Add Comment if Ticket is Missing
         if: steps.check-description.outputs.ticket-missing == 'true'
         env:
